### ISSUE TITLE
Whitelist generation

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/nxtool#3]
Given some naxsi logs, nxtool should be able to generate whitelists, for example:
- [x] cookies is a specific case of WL generation
- [x] some variables have `[` and `]` in their names (eg `array[1]=2&array[2]=1337`)

**Comment by buixor** [comment]
Whitelist generation must allow several "modes" to be used, which can be more or less specialized, for example :
  * cookies is a specific case of WL generation
  * forms is a specific case of WL generation
  * ...

Furthermore, the process should be [filters] -> [whitelist-generation] -> [whitelist-factorization]
