### ISSUE TITLE
regex support for filters

### ISSUE THREAD

**Issue by shaddai** [nbs-system/nxtool#9]
Currently filters in nxtool are static. A filter for `var_name: g-recaptcha-response` can easily be added whereas a filter for `comments: import:2016-09-29 08:22:17.215923,Whitelisted:2016-09-30 10:09:31.724727` cannot be added since the last part is modified for each event.

Could you please add a regex support for the `--filter option`. This way users could filter fields like this `--filter "comments:.*Whitelisted.*"`

**Comment by jvoisin** [comment]
@shaddai Is it working?
(I'm doing complain-driven development)
